import swaggerUi from "swagger-ui-express";
import swaggerJsdoc from "swagger-jsdoc";

const options = {
    swaggerDefinition: {
        info: {
            title: "BaroBaro API",
            version: "1.0.0",
            description: "BaroBaro API with autogenerated swagger doc",
        },
        host: "localhost:3000",
        basePath: "/",
    },
    apis: ["./src/router/*.js"],
};

const specs = swaggerJsdoc(options);

export { specs, swaggerUi };